"""add unique cycle participant constraint

Revision ID: 1539a9380540
Revises: 182c31e28ef2
Create Date: 2026-08-16 13:29:16.140450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1539a9380540'
down_revision: Union[str, Sequence[str], None] = '182c31e28ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_cycle_participant', 'cycle_participants', ['cycle_id', 'participant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_cycle_participant', 'cycle_participants', type_='unique')
    # ### end Alembic commands ###
