"""add timestamps to participants

Revision ID: 239da014a9b1
Revises: f5f39536459a
Create Date: 2026-08-19 11:34:27.826544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '239da014a9b1'
down_revision: Union[str, Sequence[str], None] = 'f5f39536459a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.add_column('participants', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('participants', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('users', 'account_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.alter_column('users', 'account_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.drop_column('participants', 'updated_at')
    op.drop_column('participants', 'created_at')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.create_table('predictions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prediction_date', mysql.DATETIME(), nullable=False),
    sa.Column('outgoing_cycle', mysql.TEXT(), nullable=False),
    sa.Column('return_cycle', mysql.TEXT(), nullable=False),
    sa.Column('confidence', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
