"""update relationships: add active status

Revision ID: 2db4bc4ae03b
Revises: a1b2c3d4e5f6
Create Date: 2026-09-02 23:18:53.522604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db4bc4ae03b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('no_self_relationship', 'relationships', 'from_participant_id <> to_participant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('no_self_relationship', 'relationships', type_='check')
    # ### end Alembic commands ###
